name: Deploy to BZU Server
on:
  push:
    branches:
      main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BZU_HOST }}
          username: ${{ secrets.BZU_DEPLOY_USER }}
          key: ${{ secrets.BZU_DEPLOY_KEY }}
          script: |
            cd ~/sample
            git pull origin main
            npm install
            pm2 restart ecosystem.config.js
